name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'   # Runs when frontend files change
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'   # Runs on PRs that modify frontend files

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Lint code
        working-directory: frontend
        run: npm run lint

      - name: Run tests
        working-directory: frontend
        run: npm run test:ci

      - name: Deploy Frontend
        run: |
          # Add deployment command for frontend
          echo "Deploying frontend"
